### PR TITLE
Support separate scrolling sidebar

### PR DESCRIPTION
**Pull request by yuehaowang**
Fixes https://github.com/pdoc3/pdoc/issues/159

I've edited css.mako to support the feature mentioned in #159 .

As `vw` and `vh` are used in my implementation, it may have compatibility problems on dated web browsers. I do not know whether it matters for pdoc. [Here](https://caniuse.com/#feat=viewport-units) is the supporting situation of `vw` & `vh` among different web browsers.

Follow-up discussions are welcome.

### CODE REVIEW

**Comment by kernc** [comment]
Evergreen browsers with graceful degradation elsewhere, that's fine. Can you fix the three scrollbars?

**Comment by yuehaowang** [comment]
Sorry, I did not noticed there are three scrollbars because my web browser (Google Chrome for macOS) hides scrollbars when they are not scrolling. It seems the third scrollbar is caused by the footer. I think putting the footer to the end of article part would fix this problem and may also have a good appearance. How do you think about this idea?

**Comment by kernc** [comment]
I certainly don't mind it. There's usually nothing too important in there.

**Comment by yuehaowang** [comment]
I've moved the footer to the article part. How about the current appearance?

**Comment by kernc** [comment]
It was quite a CSS nut to crack, but this also seems to work reasonably well, and I like it better. :smiley:

**Pull request merged**
