### PR TITLE
File INSTALL is missing

### PR DESCRIPTION
**Pull request by thebaptiste**
After having fixed the License file name (https://github.com/pdoc3/pdoc/pull/155), another problem.
I should have fixed the both problems in the same pull request...

### CODE REVIEW

**Comment by kernc** [comment]
Or I should have confirmed/checked better. :+1: Unfortunately nobody cares much about Python 2 anymore.

**Comment by thebaptiste** [comment]
In our project we use pdoc for python3 and python2 purposes, fortunately more often python 3, but sometimes python2. Thanks.

**Comment by kernc** [comment]
Just note you really shouldn't expect not even near feature parity between the two versions. Python2 is dead. :sweat_smile:

**Comment by thebaptiste** [comment]
Rest in peace...
Will you release a 0.3.13 (or update 0.3.12) on pypi ?

**Comment by kernc** [comment]
Was waiting to see if you found anything else. :smile:

Released as [0.3.13](https://pypi.org/project/pdoc3/0.3.13/). Thanks!

**Comment by thebaptiste** [comment]
Everything is ok now. I can install pdoc on dead and buried python2.
Thanks !

**Pull request merged**
